import java.util.LinkedList;

public class Day2 {

    public static void main(String[] args) {
        LinkedList<String> list = loadList();

        challenge1(list);
        challenge2(list);
        
    }

    private static void challenge2(LinkedList<String> list) {
        int processed = 0;
        int valid = 0;
        int invalid = 0;
        
        for(String s : list) {
            processed++;
            if(isValidChallenge2(s)) {
                valid++;
            } else {
                invalid++;
            }
        }
        
        System.out.println("PROCESSED: "+processed);
        System.out.println("VALID: "+valid);
        System.out.println("INVALID: "+invalid);
    }

    private static boolean isValidChallenge2(String s) {

        String[] splitS = s.split(" ");
        
        if(splitS.length != 3) {
            return false;
        }
        
        String values = splitS[0];
        String letter = splitS[1];
        String password = splitS[2];
        
        Integer min = getMin(values);
        Integer max = getMax(values);
        
        if(min == null || max == null) {
            return false;
        }
        
        char c = getChar(letter);
        
        
        return (password.charAt(min-1) == c && password.charAt(max-1) != c) || (password.charAt(min-1) != c && password.charAt(max-1) == c);
    }

    private static void challenge1(LinkedList<String> list) {
        int processed = 0;
        int valid = 0;
        int invalid = 0;
        
        for(String s : list) {
            processed++;
            if(isValid(s)) {
                valid++;
            } else {
                invalid++;
            }
        }
        
        System.out.println("PROCESSED: "+processed);
        System.out.println("VALID: "+valid);
        System.out.println("INVALID: "+invalid);
    }

    private static boolean isValid(String s) {

        String[] splitS = s.split(" ");
        
        if(splitS.length != 3) {
            return false;
        }
        
        String values = splitS[0];
        String letter = splitS[1];
        String password = splitS[2];
        
        Integer min = getMin(values);
        Integer max = getMax(values);
        
        if(min == null || max == null) {
            return false;
        }
        
        char c = getChar(letter);
        
        long count = password.chars().filter(ch -> ch == c).count();
        
        return min.intValue() <= count && count <= max.intValue();
    }

    private static Integer getMax(String values) {
        String[] split = values.split("-");
        if(split.length != 2) {
            return null;
        }
        return Integer.parseInt(split[1]);
    }

    private static Integer getMin(String values) {
        String[] split = values.split("-");
        if(split.length != 2) {
            return null;
        }
        return Integer.parseInt(split[0]);
    }

    private static char getChar(String letter) {
        return letter.charAt(0);
    }

    private static LinkedList<String> loadList() {
        LinkedList<String> list = new LinkedList<String>();
        
        list.add("4-5 m: mmpth");
        list.add("1-7 r: rszchrrrzgr");
        list.add("2-5 w: dgqtwwkwwc");
        list.add("10-11 w: ldslpwbbqwpwtd");
        list.add("3-4 s: sszss");
        list.add("1-6 l: llmjxlbt");
        list.add("8-11 c: ccctccccccw");
        list.add("1-11 l: tllllllplllzjllgz");
        list.add("5-8 j: ljjjjjjqcw");
        list.add("11-12 s: sssssqsslsvhfs");
        list.add("7-10 f: fffffmfqfffffff");
        list.add("3-8 m: mmmsqmmmh");
        list.add("3-9 w: dwzvsttjw");
        list.add("7-8 l: llllflhg");
        list.add("10-13 f: jfkwhzrtktphc");
        list.add("5-6 p: pvldppqvcd");
        list.add("9-17 s: sssssssstssssssscsss");
        list.add("4-7 k: zlwhcwkrckwkskxkgh");
        list.add("12-14 n: nnnnnnwncnnjnn");
        list.add("6-8 g: gkwzbwhgmgrqqlksswg");
        list.add("7-8 d: drpbhdvwddd");
        list.add("6-8 d: dlmphvwbnnddrd");
        list.add("5-6 m: mmzmmmpm");
        list.add("6-13 x: xdcxhkqqxznxwhtxdxt");
        list.add("4-14 c: pncwncdcccccdmwccccc");
        list.add("14-15 s: gsrsssssbsssstkssmb");
        list.add("1-3 m: dhmzmlnfmsm");
        list.add("8-12 l: llmlrllchlwhlktpxdf");
        list.add("3-5 g: njgkglgx");
        list.add("11-14 v: vvvvmwvkvtqvgxvvvlvv");
        list.add("1-4 h: hhhq");
        list.add("1-2 l: dfrmsp");
        list.add("4-5 n: nkknnkrflkpnnn");
        list.add("10-12 w: dwwwwwwlwwww");
        list.add("13-14 h: xnhhhrvwpnkmhx");
        list.add("11-12 l: lllllklrllrx");
        list.add("12-14 d: ldrvtddrddvdqgj");
        list.add("10-11 p: bxpqplqtqzhjv");
        list.add("2-5 t: bmltz");
        list.add("8-10 j: ljjjjjjmjjj");
        list.add("5-6 x: xxxvll");
        list.add("5-7 b: bxbbbbbk");
        list.add("5-11 t: ttjmsttwtdh");
        list.add("2-3 p: dmxxrpnppd");
        list.add("1-4 x: xxxxxgx");
        list.add("3-6 v: vwcvvv");
        list.add("4-5 l: lqpll");
        list.add("14-20 p: psxqnpfpnmpsppppppsp");
        list.add("16-18 g: lgggkgggggggggggglg");
        list.add("3-5 b: tbfbbg");
        list.add("6-8 n: nsnnnnnnnw");
        list.add("2-4 p: dppndlmtnt");
        list.add("11-15 q: tqqqqqqqqqqqqqq");
        list.add("13-14 r: rrrrrrrrrrrrbx");
        list.add("3-6 s: shsssfc");
        list.add("7-9 l: mlghdlhwfbcqmv");
        list.add("1-2 k: mlwk");
        list.add("13-17 v: hbvlqvknvvsvzvvvvv");
        list.add("3-4 g: bmngrgttz");
        list.add("9-10 h: hhmhhhhhtc");
        list.add("1-15 m: nmmmmmmmmmmmmmmm");
        list.add("12-13 k: kkkkkkkkkjnfckk");
        list.add("1-8 k: skkkzkkkk");
        list.add("5-7 j: jjjjjjhj");
        list.add("12-14 g: gmgxwglgggggbggqgg");
        list.add("9-11 p: pppxppqpprlgpp");
        list.add("14-15 j: cpjjjjjjjjjjjjjj");
        list.add("4-12 l: lnblzbdmpwwrbmnr");
        list.add("3-8 d: dddhdmcrddnddnddjl");
        list.add("5-9 g: kghqfsggf");
        list.add("18-20 g: gggggggggggggggggngw");
        list.add("3-5 q: rkqlqfzvwqqqksntqdz");
        list.add("8-16 m: dkmmzgmdmmmhwmxmxm");
        list.add("7-9 q: qnqhtkqqqqqqjvcs");
        list.add("1-3 m: mmlm");
        list.add("1-10 b: bjfkmblmbbtvxzp");
        list.add("4-5 c: ccldccsq");
        list.add("4-7 k: dzbkksrkkkbkwd");
        list.add("1-7 r: rrrrrrp");
        list.add("9-10 g: qgggtgnlszgggs");
        list.add("6-7 g: ggsgjfq");
        list.add("10-11 n: nnnnnnnngnnn");
        list.add("3-4 c: ftchcgcvlgzckdrg");
        list.add("13-15 p: pppnppppppppzhpplhp");
        list.add("2-7 k: xnlhlxsdzkvhw");
        list.add("5-8 m: mmmbmqmnfmtm");
        list.add("7-8 d: sdddddcjd");
        list.add("3-4 b: fnjr");
        list.add("8-14 c: cccccrjcccccccchcfqc");
        list.add("6-11 m: mmmmmmmmmmmmmmmmmmmm");
        list.add("5-7 l: lllllwhtl");
        list.add("5-7 z: zzbzrzg");
        list.add("6-10 n: ncnznxzcwvcn");
        list.add("2-4 f: xpkffxmlwtgzjppcdf");
        list.add("19-20 c: cccccccccccccxcccclf");
        list.add("4-14 w: wwlmwwfpwwzjdww");
        list.add("11-17 f: fvfffvfffffxffffff");
        list.add("12-13 s: gtshbpzgxnsss");
        list.add("5-6 m: mmsjjgmd");
        list.add("15-17 x: xxxxxxxwxxxxxxhxx");
        list.add("5-9 f: kgfjmbctt");
        list.add("6-7 k: wkknmkk");
        list.add("2-4 c: cccc");
        list.add("5-9 s: grsgskjnsmsg");
        list.add("3-5 q: qqqqqps");
        list.add("9-11 f: fffbfbfffffjfffcffkg");
        list.add("7-9 q: qqqqknqqcmqqqq");
        list.add("17-18 x: xxxxxxxxxxxxxxxxxq");
        list.add("2-10 j: cmhglhqjdg");
        list.add("10-11 h: pnhzhkgxbhkdm");
        list.add("8-12 j: qjjjjwjjjlzjbjjdcjj");
        list.add("15-16 q: qqqqqqqqqqkckvrq");
        list.add("6-15 f: fkfffffffsfcknf");
        list.add("4-17 c: vgpsglczjdfcnqtbnl");
        list.add("10-11 k: mmxktwkkwbvfkkdkkknj");
        list.add("11-12 s: ssssssspsssk");
        list.add("3-5 l: lcqdh");
        list.add("2-3 m: mqqq");
        list.add("6-7 k: fkkkjkv");
        list.add("13-15 g: gqlgdsgggggxggg");
        list.add("7-9 r: jvnkhhrrrvrsfxkrtd");
        list.add("14-15 f: ffrffffffffqpkllfxff");
        list.add("3-4 d: gjvf");
        list.add("9-12 x: hxxxrxqwxxjxxq");
        list.add("5-7 k: wdkkkdfttqkdkng");
        list.add("6-7 x: xxxvxhx");
        list.add("6-13 c: ccsclccccfmcdb");
        list.add("5-17 c: cdccsvcccccccccck");
        list.add("14-15 s: sssssssssksssnx");
        list.add("6-7 j: jjjwhqt");
        list.add("14-15 s: kssssssssssspcss");
        list.add("3-6 w: tnmlbhw");
        list.add("1-4 g: lqgrtcgn");
        list.add("1-11 b: drrwhbwzqdj");
        list.add("7-8 r: vrnvdtrr");
        list.add("4-8 w: vwwwwwwwww");
        list.add("6-7 v: vvvvvvn");
        list.add("7-14 t: sxtxhdxcwqdgrtqs");
        list.add("2-7 w: ptgsdwghvjwmwbgrqqs");
        list.add("1-2 l: llllgll");
        list.add("3-4 n: npnnbg");
        list.add("3-5 h: mxhhhwhf");
        list.add("10-15 j: bjjjtnjppjjjzcjjsw");
        list.add("8-11 r: srkkhrrcwrbrptr");
        list.add("2-4 t: qttwv");
        list.add("8-9 t: tfhtldttt");
        list.add("5-15 r: lwdmlgrrrrtrrrpxgrp");
        list.add("8-9 d: ddcddddgwd");
        list.add("3-4 b: cbbb");
        list.add("11-12 m: vmmnxtdxmmnm");
        list.add("2-5 r: rwrvc");
        list.add("1-10 s: sssxsfsssssws");
        list.add("1-4 v: kvlxvvv");
        list.add("5-17 h: dhqhhhlxhhhhqhhbhhnc");
        list.add("7-9 d: bdddpkdnfrnmb");
        list.add("3-6 x: qvstbxvkqfnxwnk");
        list.add("16-18 m: mlmpnmmstmmlmcmbmh");
        list.add("8-9 h: hhhhhhvhhhhhhhx");
        list.add("7-10 t: tqcttwwttg");
        list.add("1-9 m: gmvlmmmqmtpfm");
        list.add("3-4 p: ppppp");
        list.add("7-17 d: xddgqhdddcptxdhxc");
        list.add("1-11 f: ffffffffffff");
        list.add("13-14 r: dmsrnztgrrlvgt");
        list.add("10-11 r: rrrrrrrrrrvr");
        list.add("4-5 l: llllll");
        list.add("4-9 k: kkkkbkkkd");
        list.add("3-5 b: vsbbbtrnqzbbd");
        list.add("2-12 j: sjgjnjmhjgcjjcnjjj");
        list.add("5-15 h: lqhvhhtxkhchmhh");
        list.add("7-14 l: sllsfllllllllllllll");
        list.add("12-14 v: pvvvvvvvvvvvvv");
        list.add("4-5 j: jjgjjjg");
        list.add("11-13 q: qqqqmqqqqqdqxq");
        list.add("7-9 p: ppppppphpnp");
        list.add("5-6 s: ssrssz");
        list.add("8-14 j: jjjjjjjjjjjjjjj");
        list.add("6-8 j: jtxjdjmjxjjjrjq");
        list.add("14-16 d: ddddddddkdddddjd");
        list.add("4-6 h: hhhhwhxh");
        list.add("5-12 h: hhphwjhjhhhhhnhhbh");
        list.add("5-9 m: mmmjxhpkmmhmttjdmk");
        list.add("5-9 c: cxcvgtccttwn");
        list.add("6-11 r: bcrrwznbgtrrrr");
        list.add("3-4 t: fpttlttxjwcqmtbw");
        list.add("2-4 b: dmxkbrgpjqtlnq");
        list.add("2-7 r: rdrfprqprkgwpxrrw");
        list.add("10-13 c: ccckpcsccwccccc");
        list.add("5-7 l: vlllllkl");
        list.add("4-11 x: xxxjxxxxvxtx");
        list.add("1-5 h: hhhhh");
        list.add("7-12 s: sjssssxnssmsj");
        list.add("4-5 w: wthmw");
        list.add("6-7 f: fkppffq");
        list.add("7-8 c: cgktccccckcccc");
        list.add("1-2 q: lhnsqrk");
        list.add("2-6 m: dvmmmm");
        list.add("3-6 x: dbxxlxkf");
        list.add("7-14 d: ddsdjslpkfddxjjjkdt");
        list.add("14-16 c: ccqcvctjcccrccgc");
        list.add("1-3 d: dddrkddddkmxr");
        list.add("7-10 w: gpwgskmxsjv");
        list.add("4-5 v: bxhgm");
        list.add("6-7 w: whwhfqw");
        list.add("1-4 x: sxxxrx");
        list.add("2-4 g: ggdggg");
        list.add("15-16 h: hhhbhhhhhhhhhhhh");
        list.add("8-9 s: ssssxsksshss");
        list.add("4-6 w: wwwlwqw");
        list.add("6-8 d: sdpqddddmddw");
        list.add("14-15 j: jjjjjjjnjjjmnjj");
        list.add("2-9 p: pvzstcclp");
        list.add("18-19 g: fgggggggglpgggggztg");
        list.add("15-17 z: zzzznzzzzfzzvztzhzzz");
        list.add("10-11 j: pjjkjkjjjgj");
        list.add("7-12 w: dwbwwbzwwwbvwmwc");
        list.add("3-11 g: vgggwqnwspgg");
        list.add("8-13 w: wwwwwwczwnwtww");
        list.add("1-11 m: mjdtsvwmcqmvd");
        list.add("2-3 c: vcccc");
        list.add("6-17 k: wskkkkkkkkgjkzkkkgmk");
        list.add("8-12 g: mghgrngjggvjgg");
        list.add("4-7 p: pppsppp");
        list.add("6-9 v: vvvvvrvvv");
        list.add("5-14 j: jjmqlzjbjjjlmjjjjj");
        list.add("1-13 f: fkbnffffffffpfff");
        list.add("3-9 r: vrfrxtvwh");
        list.add("2-4 k: fkskpjkkbh");
        list.add("15-19 d: dddddddddddddddddhdd");
        list.add("1-16 s: swtmgswssfwsxpsssss");
        list.add("12-13 s: ssssssssssslssss");
        list.add("1-2 q: wvzvbb");
        list.add("9-14 d: pddddqgcdddjddx");
        list.add("4-6 x: vbqpxxbkxmx");
        list.add("1-5 q: qzqqqqqwfmtqfq");
        list.add("7-17 l: mdlcllllhrlllhpllcl");
        list.add("9-10 q: qqqqqstcgcxqqq");
        list.add("6-11 x: txtxhxxmxhxxx");
        list.add("7-8 c: ccccccppc");
        list.add("12-13 v: vmvmvvvvvvvvxvl");
        list.add("10-12 r: rrrrrzrrglrrrrkr");
        list.add("2-4 s: ssbsv");
        list.add("15-17 g: ggggggggggggggggf");
        list.add("2-7 g: sgvgtgghmtxd");
        list.add("16-17 s: ssssssssssssssvzsss");
        list.add("4-6 n: nnnnqnn");
        list.add("10-15 t: mvtttvtftqzmtjt");
        list.add("10-11 q: qqqqbqqwqrzqqp");
        list.add("6-14 h: hjhhhchhhhjhdd");
        list.add("11-15 b: zbwhdjksbqbdbmb");
        list.add("5-12 r: mrnggrwzrhrrrr");
        list.add("9-16 m: jmmmmmmmmqwmmcxmfmm");
        list.add("7-8 h: qsmhhhtsbhhhjhwl");
        list.add("2-3 h: hkghhm");
        list.add("1-4 k: nkkkk");
        list.add("3-4 z: zzzz");
        list.add("11-13 j: jrjjgbgjxrqjrmjjgckj");
        list.add("3-7 w: wwwqqlwdb");
        list.add("6-9 b: fsbbbqbbqmbb");
        list.add("13-16 n: nnnnnnnnnnnnnnnn");
        list.add("5-7 b: cbbqmbbrhbbz");
        list.add("2-3 l: xjzkbwgfwwcwll");
        list.add("13-14 z: zzzzzzzzzzzzzzzz");
        list.add("6-7 c: ccccccc");
        list.add("4-10 l: lhlslmlwmwbllv");
        list.add("4-5 h: rqhhhhh");
        list.add("3-4 t: dmtttmxhtqz");
        list.add("6-17 n: nnxcnncnnvgcnnrnrmn");
        list.add("3-4 x: xxmxxx");
        list.add("8-10 j: jjjjjjtjtvjj");
        list.add("5-11 d: ldldbnndddddsgdpgj");
        list.add("1-8 n: nsjvhncn");
        list.add("3-8 f: fffffssffxfffhl");
        list.add("1-3 q: kwnq");
        list.add("3-5 k: krkcklkhkspqmqm");
        list.add("3-4 k: dklm");
        list.add("11-14 j: jjjjjjjjjjjjjjj");
        list.add("16-17 v: vvvvvvfvvvvvvvvmx");
        list.add("5-6 m: mmmmmm");
        list.add("10-11 l: wdlgllqlslf");
        list.add("5-6 t: prbwttmtpvwr");
        list.add("6-20 c: cwcctqccthccrpccccct");
        list.add("5-12 s: sssssbssssszs");
        list.add("10-11 k: mkkjklhkktkkkdvkqqkm");
        list.add("11-12 n: nnnnrnnsngnn");
        list.add("2-5 p: ppppl");
        list.add("7-11 f: mvmdfmdwfffffwfrjfqk");
        list.add("13-16 r: rzsrdsrrrrrrprpjrb");
        list.add("13-14 c: ccccccdccccctc");
        list.add("13-18 n: nnnnnnnnnnnncnnnnnn");
        list.add("4-10 r: rvrrdhflcrtwzz");
        list.add("2-9 p: prpczpbpt");
        list.add("3-8 q: qqqqcksqqtx");
        list.add("4-5 d: xxdpmdbvddn");
        list.add("3-4 j: jjlj");
        list.add("2-3 n: nrnnnsnn");
        list.add("3-4 w: pnwkwdn");
        list.add("1-5 w: wlwgw");
        list.add("10-14 x: xxxxxxxxxxxxxxx");
        list.add("5-15 k: kkkkfskkhkkkqpf");
        list.add("3-4 b: bbbbf");
        list.add("3-4 r: jrrr");
        list.add("3-6 h: htkhhhhh");
        list.add("15-16 g: gggggggggggggvgt");
        list.add("17-18 s: ssssssssssgssssssz");
        list.add("14-15 m: pkngmmpjmxmmmms");
        list.add("4-10 f: rsmxvsghdlfff");
        list.add("16-17 z: zvzhzzczdvzkzzghg");
        list.add("16-18 v: vvvvvvvvvvvvvjvvvv");
        list.add("6-9 t: tttttmttttt");
        list.add("5-6 j: hjwxgbjf");
        list.add("3-6 k: kkkkkh");
        list.add("9-13 d: ddpgdfddddddd");
        list.add("14-15 x: xxxxxxxxxxxxxxx");
        list.add("1-4 v: vqvqkrjx");
        list.add("4-5 h: hjhhnh");
        list.add("2-3 v: jvvsrgsvfqlv");
        list.add("9-10 m: mmmmmmmmmm");
        list.add("2-5 f: ffnfpff");
        list.add("4-6 b: bbbbbg");
        list.add("8-9 p: ppjwqpjbnpppwp");
        list.add("5-6 l: lldlllll");
        list.add("9-10 g: gvgqggtgggggg");
        list.add("6-9 x: jxxxxxwxqqvxx");
        list.add("1-4 w: lwwgbt");
        list.add("16-17 d: jcdmgkmfvvlqphbddvhc");
        list.add("1-12 s: sssslssssssnsss");
        list.add("4-5 p: cjnppjllxbrp");
        list.add("13-14 n: jmzjhttnkkgnnn");
        list.add("11-12 t: vrgtrgjrdmtcfzx");
        list.add("16-17 l: lllllnmlvldlllrwmlc");
        list.add("13-16 m: mbdmmmmmmhmsmmmmtb");
        list.add("3-6 z: zszzzzz");
        list.add("1-6 h: hhhqhrbh");
        list.add("3-5 n: rlnnnn");
        list.add("17-19 x: xxxcxxxvxxxxxxxxxxkx");
        list.add("3-10 r: rccrrrhrrx");
        list.add("4-7 h: hhhdhhh");
        list.add("3-6 g: hgfzpmpgg");
        list.add("1-2 x: xxqhhx");
        list.add("5-6 m: jmmmmzf");
        list.add("1-2 j: bjjj");
        list.add("2-3 q: gqst");
        list.add("3-4 g: ggggmbghk");
        list.add("3-4 f: fnfdf");
        list.add("5-6 q: qpqtdg");
        list.add("2-3 t: ptctz");
        list.add("5-6 d: pddvdddsd");
        list.add("1-4 f: ffftff");
        list.add("3-5 b: bbdbg");
        list.add("13-17 f: fgfckcdfffftffxfffff");
        list.add("3-4 w: wwkxsw");
        list.add("2-12 l: hvgqmbqlrnzls");
        list.add("1-2 f: szff");
        list.add("6-7 q: sqqqqnqq");
        list.add("1-4 p: ppvd");
        list.add("3-7 c: cwscbkgc");
        list.add("4-12 s: sssfsssspsfsgss");
        list.add("4-10 t: jstttgststtghzp");
        list.add("5-6 j: jjjjtj");
        list.add("5-9 k: ffkdktkkhbbwkkj");
        list.add("9-15 k: kkkkkzkkkcbkkkkkkkkk");
        list.add("3-17 w: wwgwnnkswwpqwkwdhw");
        list.add("15-20 l: wlllllslllllrllllllk");
        list.add("4-5 r: rrrfm");
        list.add("2-6 l: flllnll");
        list.add("12-13 s: ssssssssssscwn");
        list.add("9-10 r: zpqrrrrrfn");
        list.add("10-13 h: xhhfhzchhjhhtdrhhzh");
        list.add("6-7 b: bbbbnrbb");
        list.add("2-12 f: tffjcjtlnvgf");
        list.add("2-4 g: gtgkg");
        list.add("11-14 n: nnnnnnbrnnnpnnn");
        list.add("15-17 j: jjjjjjjjjjjdjjvjv");
        list.add("10-13 r: brgrrrfrmfrrxrgrrrs");
        list.add("3-13 v: vwvjsftzkvcxvdbxfs");
        list.add("17-19 f: fffffffffmffffffffff");
        list.add("1-4 g: vggxg");
        list.add("5-16 m: csckdfxglfpzmrhcmbnn");
        list.add("4-15 z: gzqjzczzzzjzzhjbz");
        list.add("13-14 w: wwwlwwwwwwwwht");
        list.add("11-13 j: cjjdjjjjsjjjkjjjh");
        list.add("4-15 w: wwwqwwzwwmwwtww");
        list.add("1-2 p: ppjcp");
        list.add("6-10 f: ffjffrfffsgm");
        list.add("17-19 q: qqqqqqqqqqqqqqqqqqqq");
        list.add("3-4 g: gmgz");
        list.add("10-14 s: fpsssdmssdsgsgvss");
        list.add("9-10 m: mmmmmmmmmmmm");
        list.add("1-5 c: fcgns");
        list.add("5-9 t: ttcgtttrtttttq");
        list.add("4-5 v: vvrvvv");
        list.add("2-4 w: xwpw");
        list.add("5-12 d: trdhrqlqwrlsrdfh");
        list.add("3-8 n: bbnnnzrnnjdnb");
        list.add("8-10 w: wwwrwdwjgz");
        list.add("5-6 d: ddddjr");
        list.add("1-3 p: ppqppp");
        list.add("10-19 f: dfbjgffmpvnkhfwjfff");
        list.add("3-6 k: kkkkkkkp");
        list.add("5-7 t: vqtxtxtvk");
        list.add("14-15 c: cccclccccccctcctwc");
        list.add("2-13 x: tmxxzxklxgzxxp");
        list.add("16-17 b: bbbrbbbbbbbbbbbbbb");
        list.add("6-11 h: gmzhhhhmrhqhhm");
        list.add("7-9 k: kkkkkkqkck");
        list.add("4-7 v: pgvdvvx");
        list.add("12-19 f: fffffffffffxffffffff");
        list.add("2-5 p: mphtpp");
        list.add("6-13 t: ctttvwtntqttttq");
        list.add("3-11 t: xntrzxtlnwt");
        list.add("17-18 l: llllllllllllllllll");
        list.add("2-5 c: zczpcfdzblnkcvj");
        list.add("1-5 z: fzzzmz");
        list.add("6-11 f: tdcffpffwqlfffg");
        list.add("16-17 h: hhhhchhhhshhhhhdhh");
        list.add("13-14 m: msmmmkmmmjmmmmzmmnm");
        list.add("6-13 s: nhbscsgcssxsrsssx");
        list.add("5-17 q: qqvqqqhqrkqqqqgqqq");
        list.add("2-4 t: vqtbt");
        list.add("2-5 t: wfdrsrt");
        list.add("6-7 f: ffffzdx");
        list.add("3-13 r: pmrtkvdcrxrnrzw");
        list.add("14-18 r: wrrqrrcrrlrjmrrkrt");
        list.add("15-17 j: jjjjjjjcjjjjjjxjt");
        list.add("8-9 h: zmhhlmhhhdhhhhg");
        list.add("6-15 l: lllllnlfllllllll");
        list.add("3-5 n: nnfnb");
        list.add("16-17 s: sssssssslssssssss");
        list.add("8-9 k: kdkjkkkskkk");
        list.add("2-5 z: gzzmzhdplnwwvlsjnzv");
        list.add("4-15 r: rvmrbsrtrfdqrrb");
        list.add("6-7 l: llllllc");
        list.add("4-7 g: dnggxhgggg");
        list.add("8-9 f: fftffkdff");
        list.add("6-9 r: rrrvrprbrz");
        list.add("2-6 q: qwqqqqq");
        list.add("7-9 h: mzhpwnkhh");
        list.add("3-4 m: mmlh");
        list.add("1-15 v: vjpkvdzvzdlklpn");
        list.add("1-3 r: rrggvr");
        list.add("8-13 d: dwrpdsdjhlddqddhdwdp");
        list.add("3-4 r: fvrrsprrmrrrjgr");
        list.add("4-5 s: zsrssvss");
        list.add("6-7 d: dfdwtcvgvcdfdqdwd");
        list.add("6-12 n: rhnjnndnfnwql");
        list.add("3-5 l: hvlxlcnclqllrw");
        list.add("10-14 l: llllllllljlllplll");
        list.add("6-10 b: bbbbbbbbbbbbbbbbb");
        list.add("8-11 q: qqqqqqqtqqqq");
        list.add("7-8 r: rrrrrrxf");
        list.add("1-4 k: jkkkzsmbtng");
        list.add("13-17 r: rrrrrrlrprrdrrrrl");
        list.add("1-7 t: dfgnvtl");
        list.add("2-6 v: qvvdsm");
        list.add("8-9 l: lltlrlljb");
        list.add("3-4 m: mdmm");
        list.add("17-18 t: ttttttttttttjtxttwtt");
        list.add("9-11 b: bbbbbbbbbbpb");
        list.add("2-3 b: bwnbr");
        list.add("4-10 t: tfdtltstdft");
        list.add("8-10 z: zzfzzzztzzz");
        list.add("6-8 q: qqqqqqqmqnqqq");
        list.add("7-11 r: rzrrrrzrrrr");
        list.add("11-13 k: kkkklklbkmklk");
        list.add("17-18 l: slllllblllllllllclll");
        list.add("10-14 s: ssssssssswssssssss");
        list.add("3-4 s: hwssssgjsp");
        list.add("7-10 g: fbggxgtbngg");
        list.add("6-7 z: tzzzhzjz");
        list.add("3-7 g: ggggggcrg");
        list.add("16-20 g: grgghjcnlmkszxrgtgvv");
        list.add("1-16 n: prqnwnngbgtjsvsj");
        list.add("13-14 z: zszlgqdgtqbzzlpkzz");
        list.add("4-8 f: ffftffnnfp");
        list.add("15-18 s: jrdgssszdxkzhlsfzs");
        list.add("7-8 l: llllllbplllllll");
        list.add("7-10 l: llllbllllll");
        list.add("5-9 b: bbbbwbbblb");
        list.add("4-5 g: gdwhdg");
        list.add("2-3 v: jnfvvv");
        list.add("11-13 h: hhhhhxhhhmzhbj");
        list.add("11-13 r: wbrrrrxgwlvwd");
        list.add("10-12 m: gxmpmmmgmmmmm");
        list.add("11-12 h: hhhhzhhhhjhnhhh");
        list.add("2-13 g: kzkztgnlbqhlgx");
        list.add("4-7 z: zktzzzzx");
        list.add("1-7 q: pqrxqqhfpglwqts");
        list.add("6-7 f: pffvfbtf");
        list.add("6-7 l: tlljjlllnll");
        list.add("4-17 f: flffpffffdfqffscff");
        list.add("2-4 q: bqxqrqrrq");
        list.add("6-8 l: lllnllfll");
        list.add("9-12 r: xrgrrjrrrkgrrqrnr");
        list.add("14-19 r: rrrrrrrrrrrrrrrrrrrr");
        list.add("18-19 w: lbqrkdwwwqgrklcwxwwh");
        list.add("9-10 n: nnnnnnnnnn");
        list.add("7-13 b: bbbbbbbbbbbbb");
        list.add("5-7 k: hkbfskqkjktwkk");
        list.add("9-10 c: tlvmtfcpccwwz");
        list.add("3-7 r: rzzrspmp");
        list.add("7-11 g: gghzgglgggt");
        list.add("4-5 p: pbpwp");
        list.add("3-6 q: qqrqqv");
        list.add("3-13 m: mmmwxmmlmnvmmmmmm");
        list.add("2-6 p: ppplqpfpp");
        list.add("11-15 t: ttttttctttltctgt");
        list.add("2-7 m: cmnhjqm");
        list.add("1-6 m: mzjmtmmmmmdw");
        list.add("1-10 j: jzgjcjjjjspjjjjjgjmj");
        list.add("4-7 r: vmxtrrnrxnnq");
        list.add("8-16 h: hhhhhqhfhhhhhhhhhh");
        list.add("4-10 z: kcmkzmzpzts");
        list.add("14-15 j: jjjjjjjjjzjjjjj");
        list.add("6-11 x: xxkmxxcxxvx");
        list.add("15-16 v: vvvvvvvvvvvvvvgt");
        list.add("6-7 w: wwwwwgqz");
        list.add("5-7 d: dkdpmcddjdd");
        list.add("6-12 s: sssssssssssvs");
        list.add("8-10 q: fcpwtgqqqz");
        list.add("4-5 w: wwwwgwww");
        list.add("8-11 q: qqqqqqqnqqbqqr");
        list.add("3-4 d: dddwddd");
        list.add("9-12 x: qxcgxxxxvdxdkzxxxxx");
        list.add("3-8 k: kqcsjxszvscfvm");
        list.add("4-7 d: mgdddddhkdqb");
        list.add("3-7 x: xjxxljlsfrfnhsxxlv");
        list.add("4-9 g: xgsxgtgggxmgg");
        list.add("1-4 p: tppknptkp");
        list.add("3-7 z: gzzbzzz");
        list.add("1-5 p: ppgpz");
        list.add("15-16 f: fzfffffffffffffwff");
        list.add("5-11 t: tzttvqltfxtg");
        list.add("6-7 v: vhqvzpvv");
        list.add("2-6 f: fmffftfff");
        list.add("9-13 d: dxrdgddddrddddqpgdd");
        list.add("7-8 r: rrrrrnlnrr");
        list.add("5-6 t: btttwm");
        list.add("13-14 g: gggggggggghgblgg");
        list.add("12-19 r: qkgrvfnsrwzrqsrhrrs");
        list.add("15-17 j: jjjjjjjjjjnjjjhjd");
        list.add("4-9 t: btmrbcgttjht");
        list.add("16-17 n: nnnnnnnnvnnnnnnznn");
        list.add("3-7 l: lltlllglll");
        list.add("12-14 v: vvvvvvvvvvvvvv");
        list.add("1-3 q: qqqq");
        list.add("12-14 f: flbfphvwfdffjf");
        list.add("10-11 z: lszzzzzzzzzzz");
        list.add("3-9 k: lvzkkhkkp");
        list.add("4-6 j: fmrjccsjrzjqkfvn");
        list.add("5-11 x: xxxxvmxxxxcxx");
        list.add("1-9 c: wcccccccjxcvccccc");
        list.add("1-4 l: sblllll");
        list.add("1-2 x: xnvlnxs");
        list.add("4-5 f: nffccfff");
        list.add("8-9 p: vpppppprz");
        list.add("1-6 d: vfcqmddw");
        list.add("6-7 b: bbbbbbb");
        list.add("7-13 n: nnnnnnnnnnnnwg");
        list.add("3-6 q: zqqqqqqqqqpqqqq");
        list.add("1-9 g: gbggggdgglgmg");
        list.add("9-13 b: wbbbxnbbqbbbbkbb");
        list.add("4-5 g: gggwr");
        list.add("3-9 r: vnqvvhprzmbhrcb");
        list.add("10-11 m: mmmmmmmmmpm");
        list.add("4-7 c: cgrbccdbcz");
        list.add("5-8 r: rbvrrrrr");
        list.add("7-11 d: ddddjdmddfhvdn");
        list.add("1-2 k: zjkk");
        list.add("2-11 w: wtwwwwwwwwsw");
        list.add("7-8 b: bkbbbbfbbxd");
        list.add("2-4 w: wwnjswwmgbwrwwm");
        list.add("9-18 j: jjjjjjjjkjjjjjjjjs");
        list.add("6-7 t: tttttvwtttt");
        list.add("10-11 v: wvvvbvvvvvvvm");
        list.add("17-20 d: ddddddddddddhddddddn");
        list.add("2-12 q: qdqqqqqqqqqxqqqqqq");
        list.add("5-7 w: rjdswwwwwwqmmpww");
        list.add("1-9 b: bbbbbbbbxcbbbb");
        list.add("4-5 q: qqqwxp");
        list.add("10-15 n: nnmnnnnnncnnnnvn");
        list.add("10-17 f: fnfffffffffffffcff");
        list.add("2-3 p: krpx");
        list.add("8-10 c: cvsccclwccrcjjclc");
        list.add("5-9 t: fpnhtmtqtvwcss");
        list.add("10-13 r: rrxrrrrrrfrrrr");
        list.add("6-9 l: lllllwllt");
        list.add("11-15 n: dnnnnnnhsxgnnhsn");
        list.add("14-16 b: bbbbbbcbbbnbwkbsbm");
        list.add("3-8 g: qhlxgggqvg");
        list.add("11-14 x: ptqcgxnnhpxbgxlm");
        list.add("17-19 g: gggggggcgggbggggngg");
        list.add("10-19 q: qtjrqqwjvqqqknqbqqq");
        list.add("10-13 j: jjjjjjnjjljjsj");
        list.add("1-3 g: mggg");
        list.add("3-7 w: pwtwjdq");
        list.add("1-2 j: jjjp");
        list.add("9-13 z: pszzzglzhzzzzhz");
        list.add("1-2 j: fhhjxz");
        list.add("9-12 l: llllllllsltll");
        list.add("7-9 c: cxdvzcclccz");
        list.add("13-15 g: ggggggggfggggkgg");
        list.add("15-16 z: zjjbgzlxqzzsxzdxz");
        list.add("2-3 z: kxcszzzsrsccg");
        list.add("7-9 t: sttwxgtwlbzbsffttjb");
        list.add("1-6 r: rnmrrrtrrl");
        list.add("4-7 m: pmmtmmq");
        list.add("5-7 f: lggcpdpf");
        list.add("16-19 j: jxjjxjfssrvlmjjfjjmq");
        list.add("2-8 w: wrwswcwvw");
        list.add("4-15 k: kkkpkkkkkkkkkkq");
        list.add("12-15 s: xbssnshpsssgsbk");
        list.add("7-15 z: vzrzzczbhzzzzzzzhz");
        list.add("10-14 w: wwwwwwwwwtwwwwwwp");
        list.add("11-12 k: kkkkkkkkkkkkkckkkkq");
        list.add("15-16 s: sfssvsssssssmspl");
        list.add("4-5 d: dddqd");
        list.add("5-7 h: phsblhnfhchb");
        list.add("8-11 x: rxxxbhxxxjxxxtgsc");
        list.add("11-13 x: xxxxxxqxxxnxvx");
        list.add("5-10 p: jbpzfmphpwpz");
        list.add("9-13 v: vvvvshvvgvsfqvvvv");
        list.add("4-7 r: rrzwrzdr");
        list.add("11-13 f: fffffxffffzfwf");
        list.add("13-14 s: ssssssssssssss");
        list.add("2-11 c: czccdmkhhcvcc");
        list.add("7-11 w: wwsxwwwwwwwwj");
        list.add("7-9 t: ttknmtxvttttnt");
        list.add("1-6 r: rrpjrrrr");
        list.add("5-9 v: vkvvjqvvbvtlv");
        list.add("1-5 q: mwvhpqqqcj");
        list.add("1-5 f: fffff");
        list.add("4-5 r: trrcv");
        list.add("10-12 s: sssssssssssvss");
        list.add("4-5 d: drddzd");
        list.add("4-5 n: nnknl");
        list.add("10-12 x: xxxxfxxrzbxzvtxlxt");
        list.add("4-10 v: sbgsvssbnhmh");
        list.add("3-11 n: dnngqwnnjtnjjg");
        list.add("1-2 w: xdsvzdmzswwwwwwmgjw");
        list.add("6-8 h: whhhhmhbhh");
        list.add("2-18 w: wswwwwwwwwwwwwwwwwww");
        list.add("11-12 v: vvvvvvvvvvvv");
        list.add("7-10 v: vrhvvcvvvvvv");
        list.add("4-9 r: rrrrmzntrsgrrkhhr");
        list.add("4-5 v: vvvtvc");
        list.add("3-10 t: ttnttwzgptr");
        list.add("2-3 c: gccrngp");
        list.add("2-3 b: bbbqx");
        list.add("1-7 s: zsdlsjs");
        list.add("5-7 j: jjjjjjj");
        list.add("2-5 g: ggnhg");
        list.add("2-6 w: fwwkwhjqbwqw");
        list.add("1-6 w: wdgnjwqwqv");
        list.add("9-11 b: bbtksbbdxbpjbbbbb");
        list.add("12-15 k: kkkkkkkkkkkkkkk");
        list.add("1-6 b: bbbrbbb");
        list.add("6-7 g: gggggvs");
        list.add("8-14 s: sssnwssrsssslcs");
        list.add("1-6 q: ngjprqqmdwgkjqvq");
        list.add("11-12 z: vzzkzzgzzzzzzz");
        list.add("3-4 n: nnnnnnnn");
        list.add("5-6 b: fbwbljf");
        list.add("11-18 h: hhhhhhhhhhshhhhhhlh");
        list.add("2-15 r: rrzgrzwrblrfwfrsd");
        list.add("6-11 n: zncnknknbgn");
        list.add("13-14 f: vwffftfffpffzfff");
        list.add("5-6 c: fcccbc");
        list.add("5-6 b: bxjbcpsbrgbgn");
        list.add("2-7 f: tffhrsf");
        list.add("7-12 g: ggggggtgggggg");
        list.add("4-5 t: ktphttltctt");
        list.add("4-6 w: fwsgwh");
        list.add("7-8 m: mfmmmmmmm");
        list.add("4-5 z: gzjzzfjzzz");
        list.add("8-9 l: lvtllllllll");
        list.add("3-5 m: rsmmd");
        list.add("10-11 r: rrrrrrrrrlz");
        list.add("11-13 j: hhqtkwznghbfsbwpvrj");
        list.add("4-5 z: zjzndzrmqzlptg");
        list.add("13-16 m: mmhmmmmmmmmmpmrmmm");
        list.add("5-7 p: pppphpp");
        list.add("2-3 s: zscgsj");
        list.add("14-15 h: hhhhhhhhhhhhhlhh");
        list.add("2-3 f: rffrtlxwfff");
        list.add("1-3 z: ptqlzzxskrjsnp");
        list.add("3-4 t: ftttst");
        list.add("8-9 t: thtttttpttm");
        list.add("11-13 g: qzhmgptdfwggqqc");
        list.add("6-9 f: nfffhfkffhf");
        list.add("2-3 w: qsxgww");
        list.add("11-12 d: ddddddddddddd");
        list.add("2-4 v: qsbvvv");
        list.add("8-13 z: zxczszkwxzgkz");
        list.add("2-4 t: cbtt");
        list.add("2-5 q: clndcnv");
        list.add("8-12 f: kfnhqbfnnpntfsvxcx");
        list.add("2-3 d: gddtd");
        list.add("1-9 z: tztzzzdnm");
        list.add("3-7 h: hhhhhhhhh");
        list.add("5-6 t: tttttvtttt");
        list.add("5-9 g: npzggdhvggpqgxwgvgsg");
        list.add("3-12 p: kwpptpplxrcgfxphpqbg");
        list.add("15-18 f: fffjffffffffffwffff");
        list.add("7-17 n: nnnnnnnnnnnnnnnnnnnn");
        list.add("5-10 d: dndddkddddx");
        list.add("1-7 v: cvhvsvhvv");
        list.add("5-7 f: fscrtxlz");
        list.add("1-14 b: bbbbbbbbbbbbbbb");
        list.add("1-11 n: nnlnxntnlxnnnktnnxb");
        list.add("13-18 p: pppzppppfqhppppzrp");
        list.add("7-8 h: hhhhzhhmqhh");
        list.add("16-17 r: rrrrwrrrrrrrrxrrrr");
        list.add("4-8 f: wfffgnff");
        list.add("15-16 j: jswvgtfhtffjgjjsxsdq");
        list.add("16-17 n: nnnsnnnnnnnnnnnnnnn");
        list.add("7-8 w: dxhcjvwwzwdddhhwwlj");
        list.add("1-13 h: ppshfshghphcq");
        list.add("5-15 b: cbxnbhbbjbhbbmbkvz");
        list.add("2-11 c: tdgcqlcccccthwmk");
        list.add("1-4 p: mpppp");
        list.add("1-4 x: xpzxxkzlrsgrbxpklcz");
        list.add("2-11 f: qffffgfffcgn");
        list.add("14-19 h: hhhhhhhhhhhhhsbkhhqh");
        list.add("9-12 h: hclhhhpsvhhfhh");
        list.add("2-6 s: lqcppxlsfv");
        list.add("6-9 v: vvvvvnvvv");
        list.add("9-10 q: xqqqqqqqqqq");
        list.add("3-8 m: qmmcjmvmckrmm");
        list.add("4-9 h: hhhdhfhhs");
        list.add("1-14 r: vpsprlstjkrmmrpzqsz");
        list.add("6-7 g: ggggrlqg");
        list.add("7-10 t: dtkttptttttt");
        list.add("3-4 n: vkkf");
        list.add("9-11 g: gflgwgggrgmmggg");
        list.add("3-19 l: blblmlrlllhbllwllll");
        list.add("12-13 x: gvxsxkrvdqbxx");
        list.add("11-12 b: bbbbdpdbbwls");
        list.add("2-13 n: nnnnnnnnsnnnrnnnnn");
        list.add("6-13 n: mfnnnnnkxnnnn");
        list.add("5-6 f: kxxfqnf");
        list.add("4-5 x: xxxxl");
        list.add("6-13 f: nsnxwrftkcgzffv");
        list.add("6-7 w: wwpwwxl");
        list.add("5-7 m: brvmmnw");
        list.add("1-4 r: rkbhnmdt");
        list.add("9-10 b: knbzbbfnfbbblrqbrbnj");
        list.add("2-5 v: vvvxvvxbw");
        list.add("3-5 q: qcsjq");
        list.add("7-15 c: gcdpccrcddccwccf");
        list.add("13-14 h: hhhhhhhhhhhhhh");
        list.add("10-11 l: rllllllllllpcs");
        list.add("10-11 w: wwwwwwwwwfw");
        list.add("2-7 f: fxtfffn");
        list.add("3-5 x: xxxkx");
        list.add("3-6 c: ccrrwbsj");
        list.add("1-4 g: gggggpgqgg");
        list.add("1-2 t: vztj");
        list.add("4-11 c: zccccccccqcc");
        list.add("5-11 p: hbpzppdlppp");
        list.add("3-5 h: frhhhzhprz");
        list.add("4-7 d: mzdnddd");
        list.add("15-16 t: gttttttttqttntttc");
        list.add("1-8 c: ccqcjbhpccczvfck");
        list.add("2-3 b: lztcb");
        list.add("4-5 d: ddddd");
        list.add("2-8 j: pwfjfdjjjjzkjcjrlwr");
        list.add("10-11 m: qmmmmmjnmpmmmmxn");
        list.add("10-17 f: ppbfdsjvpfhzccbwfr");
        list.add("4-8 c: cfnhqtcmcws");
        list.add("4-6 b: bbqxpfzqfvkpbhcbdfn");
        list.add("4-5 k: kkkkx");
        list.add("4-8 f: vpwfkfff");
        list.add("1-3 t: ttxtvtthttg");
        list.add("3-4 j: fjjj");
        list.add("18-19 v: vvvvvvvvvvvvvgvvvxp");
        list.add("11-14 q: qqqqqqqqqqqqqq");
        list.add("2-3 p: ppplxprwvjmf");
        list.add("7-14 q: qpqxzqqqqqqgqmgqqgq");
        list.add("3-7 x: dqlxtkx");
        list.add("6-7 f: sfczgfffzfhffjkkf");
        list.add("1-4 x: xxxxfwxxxpmxd");
        list.add("4-5 b: jbbbbb");
        list.add("10-11 p: vrpvpppppppdppp");
        list.add("18-19 l: llllllllllllllllllll");
        list.add("4-10 v: jjzvnsfbbvqcdfq");
        list.add("16-18 d: ddddddddddddddddddd");
        list.add("13-14 t: ftttdtkrdtktttlttkd");
        list.add("3-17 d: ddkddfldddddddddr");
        list.add("10-20 v: hfzhttvvnkxqvvhlvvvq");
        list.add("5-6 t: tbwtszgwpntthtvttrsj");
        list.add("5-6 s: ssshsstds");
        list.add("2-4 h: hhhb");
        list.add("6-7 b: bbsbfbb");
        list.add("2-12 n: znvqnslfhnwnqr");
        list.add("16-17 g: gggkggggggggggggl");
        list.add("4-12 j: vjqdjjjtsjdjv");
        list.add("14-16 j: jjjdjljjjjjjjjjjjp");
        list.add("4-14 d: dddddtqdddddddd");
        list.add("3-4 m: mpmm");
        list.add("7-8 c: ccccccdc");
        list.add("3-8 l: clllhnlllrzzgll");
        list.add("9-10 c: ccccccccbx");
        list.add("3-4 k: kkkj");
        list.add("5-12 r: rrrtjxhxzbrrf");
        list.add("4-6 w: wwwkwhww");
        list.add("7-9 m: fqrmrmmmmgmmmtmb");
        list.add("3-11 w: kwwnwwwghhgw");
        list.add("9-11 k: kkkkkkpkkkktvkkk");
        list.add("5-9 w: hwqjflkkwdqmwmcw");
        list.add("12-16 h: hmhmhhhkxhghhhhhhhhh");
        list.add("1-4 z: zjzlhjpft");
        list.add("1-6 d: dddqdd");
        list.add("1-9 s: ssssssssss");
        list.add("2-4 d: wddf");
        list.add("7-9 k: nhzkkmkxkhkphkdkkd");
        list.add("12-15 m: khmmmmmmhgmmmmmmm");
        list.add("3-9 n: jnknnnnnn");
        list.add("6-8 g: ntgggfggmlrgcggf");
        list.add("12-15 g: gggghggggmgmggdgg");
        list.add("7-13 x: rxxxxxrxxxxxnqxwsxx");
        list.add("3-5 n: bnnbnnvdwnls");
        list.add("3-5 v: mvbnzk");
        list.add("2-8 n: npntnnnjnxknb");
        list.add("6-11 t: ttftttlqtttt");
        list.add("5-7 g: ggggmgp");
        list.add("5-7 x: xxbjcxw");
        list.add("1-8 d: ddddldddddddwdddd");
        list.add("2-4 s: csswjbfnjnm");
        list.add("3-4 m: mmmr");
        list.add("16-17 z: zzsspzjzzzzzznzzz");
        list.add("3-4 r: rvzpfr");
        list.add("3-5 p: wpgxpb");
        list.add("4-5 r: qlrrr");
        list.add("7-9 q: vqzzqqrqtf");
        list.add("6-14 c: qcfwcfcchcvzzgcl");
        list.add("2-11 r: brhlrbvrlrrr");
        list.add("7-13 l: lllllllllrlllll");
        list.add("2-7 w: twfwwdwvzwbw");
        list.add("4-5 z: zzzbzz");
        list.add("3-4 q: qzzt");
        list.add("3-11 h: hhhhhhhhhhhh");
        list.add("5-12 c: cdclccgcccxfczrlcc");
        list.add("5-11 p: lmgprpppvphpj");
        list.add("2-5 r: rgkqrdsrxlmddmkktpnr");
        list.add("1-4 m: zmgfmqmmmxfm");
        list.add("15-16 f: ffbffffffffffwvnf");
        list.add("19-20 l: ltllllllllllllllllhl");
        list.add("2-6 j: spthjkftw");
        list.add("3-10 r: rrrrrrfrrmrrrr");
        list.add("1-8 n: nndfhqxn");
        list.add("6-7 j: zjjjjjj");
        list.add("12-14 k: qvgcvhmzkkrcck");
        list.add("6-8 k: kkhbkhkkkk");
        list.add("10-12 s: ssrssxssslsj");
        list.add("9-18 h: dsmxxwndhgjpztkqhh");
        list.add("5-6 m: mmmmlf");
        list.add("4-5 x: xxxlh");
        list.add("9-15 b: bbbcsgbdcbbrbrfbbbbb");
        list.add("6-15 j: nfbjrpjjqjjxsbjt");
        list.add("1-6 c: cncpkcfwcd");
        list.add("2-4 m: xmmhmjbcmdmm");
        list.add("4-11 s: lhdssvkldhsqssdjgs");
        list.add("14-19 t: ttttttdtttttlttttttt");
        list.add("2-4 x: gxxxbxk");
        list.add("2-6 k: kkpqkkkz");
        list.add("10-11 w: wwwqwwwwcgqwww");
        list.add("8-9 s: sssssssss");
        list.add("2-4 v: vvvwsrb");
        list.add("12-16 s: rtcsfwssdswthfpf");
        list.add("3-11 g: fgnggtlgbgd");
        list.add("2-5 c: ggccc");
        list.add("10-15 h: hhhhhhlhpghhshh");
        list.add("1-5 n: nlhqnj");
        list.add("7-10 f: fnfffffhffff");
        list.add("5-6 t: tfttkvt");
        list.add("1-4 c: mgcsrv");
        list.add("10-17 g: bggpmggggpgggggwqh");
        list.add("3-7 p: pprvppp");
        list.add("5-8 n: xnnqndnznf");
        list.add("6-11 b: bbbbrbfbrcdb");
        list.add("3-10 k: pcfknlqkgkpzkknk");
        list.add("10-11 m: mmmmmmmmmmc");
        list.add("3-4 v: fwvvh");
        list.add("2-7 l: zlcvxwrhlnnlkhr");
        list.add("1-7 q: vqqqjqsqqqqvrqqq");
        list.add("6-8 d: ddddddddd");
        list.add("1-3 z: zkzlrz");
        list.add("5-11 w: wbfzwdwpwdfztsrxzcw");
        list.add("7-9 s: qsssclssl");
        list.add("3-5 l: cvmlgk");
        list.add("9-12 s: qsrssnsvsxshqsdtd");
        list.add("8-12 m: wmxsnmmmfwzmf");
        list.add("1-12 x: xxxxxdxxjxxdxxxxxx");
        list.add("4-10 r: rwrlbkkmqrxr");
        list.add("5-13 g: ggggggggghgggx");
        list.add("11-15 w: wwwwtwnwwwvwwft");
        list.add("9-10 q: qqqqqqqqwfq");
        list.add("6-13 q: qmhfqqxkmcjwqmc");
        list.add("2-8 r: rrrrcmrrrrq");
        list.add("12-14 m: mmmwmmmmmgmhmt");
        list.add("2-6 t: ttvtctt");
        list.add("3-6 r: qcrrpsxjttqrrr");
        list.add("7-8 g: gggggggk");
        list.add("13-15 w: wwwwwwwwwwwwwww");
        list.add("8-12 p: qqphwpjmwppfpvwrp");
        list.add("7-10 c: cccccwtccc");
        list.add("8-11 w: kwtwrwwwwcqwww");
        list.add("9-19 z: zzzzzzzzzzzzzzzzzzz");
        list.add("4-5 q: qqqsq");
        list.add("6-9 c: cxfcccgcccpc");
        list.add("7-9 d: nddlddxdgddzd");
        list.add("3-12 q: qrghqxqjqqdwqqq");
        list.add("14-15 w: wwwwwwwwwwwwwqmwwww");
        list.add("14-15 c: frcwcctccrccccc");
        list.add("2-5 v: vqvvdvv");
        list.add("3-4 r: rsrr");
        list.add("16-18 d: dddddddddddddddtdxdd");
        list.add("4-7 b: bfbbbbsbj");
        list.add("14-15 b: bbgbbbbbbfbbmbbbmb");
        list.add("2-7 b: pbrsbbb");
        list.add("15-16 q: qqqsqqqqqqqbnqqqqq");
        list.add("6-14 k: rbvkkvqrxfklck");
        list.add("2-6 c: klccdm");
        list.add("2-3 b: bpbbs");
        list.add("4-13 p: cppjppppppppmvpppp");
        list.add("1-2 k: kqkpq");
        list.add("8-9 r: rrrrrhrkr");
        list.add("7-9 t: tptftttgwtmt");
        list.add("8-12 g: gfhkgqggznqghqg");
        list.add("15-18 n: pnnnnnnnnnnnnnnnnnn");
        list.add("4-5 p: qpqpq");
        list.add("1-9 h: xhqhhhnthzmhhhrh");
        list.add("4-6 x: bzkxxxhxxwdzpkks");
        list.add("4-5 c: ccccc");
        list.add("9-10 v: vvvvvvvvvv");
        list.add("8-12 d: cdcxdzgddtcfdrxt");
        list.add("7-10 b: bbbsbpbbgbbnj");
        list.add("4-7 z: zznzzzq");
        list.add("1-5 z: zjbzzjdppsbvgbg");
        list.add("2-4 w: lwwwtvjwdjwsbps");
        list.add("1-2 z: bzbvbz");
        list.add("6-14 n: dnnnnqnnnnnnnn");
        list.add("15-18 r: rfbrrwqshczrnbxrvhzr");
        list.add("9-11 f: ffffffffpfz");
        list.add("1-4 k: rskn");
        list.add("5-6 n: njnnnb");
        list.add("3-5 z: zzzzz");
        list.add("7-8 n: nntnnnnn");
        list.add("8-14 k: kkkkkkfkkkkkkkkk");
        list.add("11-16 r: rrqrprrrrrrrrrsvrr");
        list.add("2-10 c: dncjfccpcccccccc");
        list.add("8-20 q: gztqpsqqvthwpfjlqxrq");
        list.add("6-16 n: nnnnnpnnnnnnnnbnnnnn");
        list.add("4-7 h: ghhhwzhhhhhh");
        list.add("10-12 z: zzqzzzcfxzzzwzz");
        list.add("1-3 k: tlkwlkskklxvnk");
        list.add("12-13 n: nnnqqnnnnnnfpn");
        list.add("1-3 l: lnlb");
        list.add("6-9 b: bvfkbrzbwdmbvbql");
        list.add("11-13 d: ddddtdwtjdkdqz");
        list.add("9-15 j: jjcljjjjqjvnjjfjjj");
        list.add("13-14 l: tpllllllllqlll");
        list.add("18-20 d: dddddddddddzdddddtdb");
        list.add("9-15 x: nxxxmnxxxxxxsxxxjwg");
        list.add("6-7 j: rjwvjzjjx");
        list.add("5-6 j: jjjjjjj");
        list.add("8-13 t: ttfttttttttttt");
        list.add("6-16 f: ffrffxfffffffffmf");
        list.add("3-4 f: mhxk");
        list.add("4-9 w: lnwnwwvtvwjww");
        list.add("9-12 d: dwdddqddpdddd");
        list.add("11-16 q: qqqqqqqjzqqpqqlq");
        list.add("2-14 k: zkskkmkrwrdkskq");
        list.add("5-8 v: vqxmvxvvj");
        list.add("3-5 z: zpbwzhrzzwqxr");
        list.add("3-5 c: cccgc");
        list.add("6-9 v: vvvtbvvvvtj");
        list.add("5-6 f: fjwfgdfgtf");
        list.add("1-2 s: svvsnsk");
        list.add("11-13 f: qfpwfmrcfcwfr");
        list.add("3-6 j: jjjxdd");
        list.add("3-6 n: kntwpnn");
        list.add("8-13 v: qgmgcrxvdvkbs");
        list.add("11-16 q: cqsqpqlzqqdhqcqrbgk");
        list.add("1-8 t: pptttttt");
        list.add("11-13 g: ggggggggggkgqgg");
        list.add("4-5 g: gggsgg");
        list.add("10-11 p: rpppfppppmpppp");
        list.add("6-7 q: qqqqqqq");
        list.add("3-11 f: pgfftfflctfd");
        list.add("3-8 s: lswnfsjjdsh");
        list.add("11-13 k: kkkkkkkkkkmksk");
        list.add("3-5 p: pppjpppg");
        list.add("3-4 z: zznrz");
        list.add("8-9 d: ntgdwtdmh");
        list.add("2-3 g: gggl");
        list.add("19-20 q: qqqqqxqqqqqqqqqqqqwd");
        list.add("4-11 n: ljgdnkgftmsvntnn");
        list.add("16-19 t: tttttttttttttttttttt");
        
        return list;
    }

}
